### ISSUE TITLE
Bug Found — Coordinates Not Plotting

### ISSUE THREAD

**Issue by wonmor** [GameGenesis/First-Principles#3]
Using one of the function classes I made, the coordinates corresponding to the user input equation successfully get transferred over to the data point section on the main class function; however, the graph does not show up on the screen for some reason. FIX THIS NOW OR YOU'RE FIRED.

**Comment by GameGenesis** [comment]
This issue has now been fixed!
The error was that the LineRendererUI Script was disabled in the editor, although, when enabled, functions did not plot correctly!
